language: ruby
rvm:
- 2.1.0
- 2.0.0
- jruby-19mode
- rbx-2
- ruby-head
deploy:
  provider: rubygems
  api_key:
    secure: kaHhG0D7M5ImRK0AoO5UsdcAKRtms57Mix6lzJIK+tYADnDQFRGDTZ/odUYkwup5dwW1zX/GkehEee6zEvmxnwgQz3+qAf4NSR7lqSzvD5Q4ZssLt6tw2jEmKijG/0MUTGojtPidPcR/wDpsxDdasBvxuFTObaLTTdATCiy2wRM=
  gem: enumerator_concurrent
  on:
    all_branches: true
    tags: true
    repo: doodzik/enumerator_concurrent
